version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
    
- package-ecosystem: gradle
  directory: "/"
  target-branch: "1.8.9-backport"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  
- package-ecosystem: gradle
  directory: "/"
  target-branch: "1.12.2"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  
- package-ecosystem: gradle
  directory: "/"
  target-branch: "1.14.4"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  
- package-ecosystem: gradle
  directory: "/"
  target-branch: "1.15.2"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  
- package-ecosystem: gradle
  directory: "/"
  target-branch: "1.16.5"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  
- package-ecosystem: gradle
  directory: "/"
  target-branch: "1.18.2"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  
- package-ecosystem: gradle
  directory: "/"
  target-branch: "1.19.2"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
