modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/MC-U-Team/Music-Player/issues"
displayURL="https://u-team.info/mods/musicplayer"
logoFile="logo.png"
license="Apache-2.0 License"
credits="Thanks to sedmelluq for making lavaplayer"
authors="HyCraftHD"

[[mods]]
	modId="musicplayer"
	version="${file.jarVersion}"
	displayName="Music Player"
	updateJSONURL="https://api.u-team.info/update/musicplayer.json"
	description="Play every youtube video, livestream and more with this player! We use lava player to ensure this diversity.\n\nLearn more about lavaplayer here: https://github.com/sedmelluq/lavaplayer\n\nSources:\n  - YouTube\n  - SoundCloud\n  - Bandcamp\n  - Vimeo\n  - Twitch streams\n  - Local files\n  - HTTP URLs\n\nFile formats:\n  - MP3\n  - FLAC\n  - WAV\n  - Matroska/WebM (AAC, Opus or Vorbis codecs)\n  - MP4/M4A (AAC codec)\n  - OGG streams (Opus, Vorbis and FLAC codecs)\n  - AAC streams\n  - Stream playlists (M3U and PLS)"
	
	[[dependencies.musicplayer]]
	    modId="forge"
	    mandatory=true
	    versionRange="[34.0.1,)"
	    ordering="NONE"
	    side="BOTH"
	
	[[dependencies.musicplayer]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.16.3]"
	    ordering="NONE"
	    side="BOTH"
	    
	[[dependencies.musicplayer]]
	    modId="uteamcore"
	    mandatory=true
	    versionRange="[3.1.9.181,)"
	    ordering="NONE"
	    side="BOTH"